name: Sync Time Entries

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
      CLOCKIFY_WORKSPACE_ID: "630f768292cc4b674e5ae3e4"

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create sync script
        run: |
          cat > scripts/sync-all.ts << 'EOL'
          import { TimeEntriesService } from "../src/services/timeEntries";

          async function syncAll() {
            try {
              const timeEntriesService = TimeEntriesService.getInstance();
              await timeEntriesService.syncAllEmployeesTimeEntries();
              console.log("Successfully synced all time entries");
            } catch (error) {
              console.error("Error syncing time entries:", error);
              process.exit(1);
            }
          }

          syncAll();
          EOL
          
      - name: Run sync
        run: npx ts-node scripts/sync-all.ts
